Parameters:
  EnvironmentName: 
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DE-Extract

  KeyName:
    Description: Select the key pair to use for decrypting the Windows instance password.
    Type: AWS::EC2::KeyPair::KeyName

  VPC:
    Description: Select the VPC Id
    Type: AWS::EC2::VPC::Id

  Subnet:
    Description: Select the Subnet Id
    Type: AWS::EC2::Subnet::Id

  SecurityGroupIds:
    Description: Select one or more Security Groups
    Type: List<AWS::EC2::SecurityGroup::Id>

  LatestWindowsAmiId:
    Description: The latest Windows Amazon Machine Image (AMI) Id
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base

Resources:
  WindowsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
    DeletionPolicy: Delete

  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: WindowsInstanceRole

  WindowsInstanceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "Windows-client-${AWS::StackName}"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource: "*"
      Roles:
        - Ref: WindowsInstanceRole
    DeletionPolicy: Delete

  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestWindowsAmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref Subnet
          GroupSet: !Ref SecurityGroupIds
      IamInstanceProfile: !Ref WindowsInstanceProfile
      Tags:
        - Key: Name
          Value: DE-Extract-Windows-Instance

